# Generated by Django 4.0.6 on 2022-08-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='percas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('descricao', models.CharField(max_length=40, verbose_name='descrição')),
                ('valor_compra', models.FloatField(verbose_name='valor_compra')),
                ('valor_venda', models.FloatField(verbose_name='valor_venda')),
            ],
        ),
    ]
