# Generated by Django 4.0.6 on 2022-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('senha', models.IntegerField(verbose_name='senha')),
                ('name', models.ImageField(upload_to='', verbose_name='name')),
            ],
        ),
    ]
